const FETCH_QUIZES_START = "FETCH_QUIZES_START";
const FETCH_QUIZES_SUCCESS = "FETCH_QUIZES_SUCCESS";
const FETCH_QUIZES_ERROR = "FETCH_QUIZES_ERROR";

const FETCH_QUIZ_SUCCESS = "FETCH_QUIZ_SUCCESS";
const QUIZ_SET_STATE = "QUIZ_SET_STATE";
const FINISH_QUIZ = "FINISH_QUIZ";
const QUIZ_NEXT_QUESTION = "QUIZ_NEXT_QUESTION";
const RETRY_QUIZ = "RETRY_QUIZ";

const CREATE_QUIZ_QUESTION = "CREATE_QUIZ_QUESTION";
const RESET_QUIZ_CREATION = "RESET_QUIZ_CREATION";

const AUTH_SUCCESS = "AUTH_SUCCESS";
const AUTH_LOGOUT = "AUTH_LOGOUT";

export {
  FETCH_QUIZES_ERROR,
  FETCH_QUIZES_START,
  FETCH_QUIZES_SUCCESS,
  FETCH_QUIZ_SUCCESS,
  QUIZ_SET_STATE,
  FINISH_QUIZ,
  QUIZ_NEXT_QUESTION,
  RETRY_QUIZ,
  CREATE_QUIZ_QUESTION,
  RESET_QUIZ_CREATION,
  AUTH_SUCCESS,
  AUTH_LOGOUT
};
